name: Build and Test
on:
  push:
    branches: [master]
  pull_request:
    type: [synchronize]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Dhall
        uses: dhall-lang/setup-dhall@v4
      - uses: cachix/install-nix-action@v12
        with:
          nix_path: nixpkgs=channel:nixos-21.05
      - name: Dhall test
        run: |
          dhall-to-json <<< "./pipeline.dhall"
      - name: build
        run: nix-build
